# Home Assistant addon definition file

name: Miele REST Server
version: "1.1.1"
slug: miele_rest_server
description: Run MieleRESTServer as a Home Assistant add-on.
url: https://github.com/hannesdelbeke/MieleRESTServer
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
ports:
  5001/tcp: 5001
ports_description:
  5001/tcp: MieleRESTServer REST API
map:
  - type: config
    read_only: false
options:
  debug: false
  endpoints: []
schema:
  debug: bool
  endpoints:
    - name: str
      host: str
      groupId: str
      groupKey: password
      route: str?