name: Add-on Validation

on:
  pull_request:
    paths:
      - 'miele_rest_server/**'
      - '.github/workflows/addon.yml'
  push:
    branches:
      - main
    paths:
      - 'miele_rest_server/**'
      - '.github/workflows/addon.yml'

jobs:
  build-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build add-on image
        run: docker build miele_rest_server
